#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os


todo = ["botlib", "botd", "genocide", "rssbot", "gcid", "evrm", "kamer", "koning"]


def popen(*args, **kwargs):
    c = 0
    for l in os.popen(*args, **kwargs):
        if not c:
            print(l.strip())
        c += 1


def main():
    for td in todo:
        print("processing %s" % td)
        os.chdir(td)
        popen("dev/clean")
        popen("python3 setup.py sdist")
        popen("cp dist/* ../tar")
        popen("dev/clean")
        os.chdir("..")


main()