#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os


todo = ["botlib", "botd", "rssbot", "newobj"]


def popen(*args, **kwargs):
    c = 0
    for l in os.popen(*args, **kwargs):
        if not c:
            print(l.strip())
        c += 1

for td in todo:
    print("cloning %s" % td)
    popen("git clone ssh://git@github.com/bthate/%s w/%s" % (td, td))
