#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import os
import shutil
import sys
import unittest


sys.path.insert(0, "lib")


from op import Class, Config, format


Config.workdir = ".test"


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS
results = []


def main():
    if os.path.exists(".test"):
        shutil.rmtree(".test")
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)


main()
